trigger: none

pool: todoinfra

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
    backendServiceArm: 'todoinfra'
    backendAzureRmStorageAccountName: 'nexgenstg123'
    backendAzureRmContainerName: 'gennexcontainer'
    backendAzureRmKey: 'gennex.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
    environmentServiceNameAzureRM: 'todoinfra'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
    environmentServiceNameAzureRM: 'todoinfra'