name : deploy
run-name : Action show
on : 
  push :
    branches :
      - main 
      - feature/123

jobs : 
  deploy-job:
    runs-on : ubuntu-latest
    steps :
      - name : new massage
        run : echo "I Have Done This"
