name : deploy
run-name : Action show
on : 
  push :
    branches :
      - main 
      - feature/123

jobs : 
  job-deploy:
    runs-on : ubuntu-latest
    steps :
      - name: this gone work
        run : echo "I Have Done This"
